include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "lab06")
set(CPACK_PACKAGE_VENDOR "vanishhhhh")
set(CPACK_PACKAGE_CONTACT "vanpanvit@gmail.com")

set(CPACK_PACKAGE_VERSION ${PRINT_VERSION})

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Solver application package")
set(CPACK_PACKAGE_DESCRIPTION "Solver application for solving quadratic equations")

set(CPACK_DEBIAN_PACKAGE_NAME "lab06")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "vanishhhhh <vanpanvit@gmail.com>")
set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

set(CPACK_RPM_PACKAGE_NAME "lab06")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "utils")
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DMG_VOLUME_NAME "lab06")
set(CPACK_DMG_FORMAT "UDZO")

set(CPACK_WIX_UPGRADE_GUID "E9E84C5E-8F5D-4B9B-A0E3-4C0F2F0C3A61")

include(CPack)